{
    "openapi": "3.0.0",
    "info": {
        "title": "my-clothing",
        "version": "0.0.1"
    },
    "servers": [
        {
            "url": "http://localhost:8888",
            "description": "本地主機"
        },
        {
            "url": "http://dev.laravel-sail.site:8080",
            "description": "expose主機"
        }
    ],
    "paths": {
        "/api/carts": {
            "get": {
                "tags": [
                    "Carts"
                ],
                "summary": "個人購物車存貨列表",
                "operationId": "88963ab10a86ebeb4e81c70489a3ee39",
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/myCartProducts"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Carts"
                ],
                "summary": "將存貨加入購物車(覆蓋之前的紀錄)",
                "operationId": "06affd160606e43fb60f39628e5bd33a",
                "requestBody": {
                    "request": "CartsRequestBody",
                    "description": "存貨和數量列表",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/inventoryReqs"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "請求成功"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Carts"
                ],
                "summary": "清空購物車",
                "operationId": "29e2143e50f31dc4ef0489e1c0f208c5",
                "responses": {
                    "204": {
                        "description": "請求成功"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/carts/{cart_id}": {
            "delete": {
                "tags": [
                    "Carts"
                ],
                "summary": "將指定商品從購物車移除",
                "operationId": "e2d94f80ed020a3d857efbc01ef0c219",
                "parameters": [
                    {
                        "name": "cart_id",
                        "in": "path",
                        "description": "購物車內商品id",
                        "schema": {
                            "type": "integer",
                            "default": 1
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "請求成功"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/carts/checkout": {
            "post": {
                "tags": [
                    "Carts"
                ],
                "summary": "清空購物車並扣除存貨",
                "operationId": "6254f60ab96821458733625399920218",
                "responses": {
                    "204": {
                        "description": "請求成功"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/inventories": {
            "get": {
                "tags": [
                    "Inventories"
                ],
                "summary": "存貨列表",
                "operationId": "14778f5d86f3e51cab479d0cf398aac1",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "存貨 id",
                        "schema": {
                            "type": "string",
                            "default": "1,2,3,4,5"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/inventoriesForChart"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "需填入存貨id",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "message": "inventories id is required"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "tags": [
                    "Products"
                ],
                "summary": "商品列表",
                "operationId": "1bfaa78d1c2c3848ab8165c5dadcad3e",
                "parameters": [
                    {
                        "name": "category",
                        "in": "query",
                        "description": "分類名稱",
                        "schema": {
                            "type": "string",
                            "default": "上衣"
                        }
                    },
                    {
                        "name": "find",
                        "in": "query",
                        "description": "商品名稱模糊查詢",
                        "schema": {
                            "type": "string",
                            "default": "T恤"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/products"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "分類名稱有誤",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "message": "category name error"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/products/{product_id}": {
            "get": {
                "tags": [
                    "Products"
                ],
                "summary": "根據商品id，查找指定商品",
                "operationId": "3b646880fbf58e1a9d37fad9bfed30bb",
                "parameters": [
                    {
                        "name": "product_id",
                        "in": "path",
                        "description": "商品id",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "default": 2
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/productsWithInventories"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "商品id有誤",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "message": "product id does not exists"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/products/recommend": {
            "get": {
                "tags": [
                    "Products"
                ],
                "summary": "隨機生成5個推薦商品",
                "operationId": "7c3fd50e975b23a0f8445b86b14d8d88",
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/products"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "註冊會員",
                "operationId": "f1fde7f4a932e393f6042d1b92e65b0a",
                "requestBody": {
                    "request": "RegisterRequestBody",
                    "description": "註冊會員的請求範例",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "example": "allen"
                                    },
                                    "email": {
                                        "type": "string",
                                        "example": "allen@example.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "12345678"
                                    },
                                    "password_confirmation": {
                                        "type": "string",
                                        "example": "12345678"
                                    },
                                    "phone": {
                                        "type": "string",
                                        "example": ""
                                    },
                                    "address": {
                                        "type": "string",
                                        "example": ""
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {}
                        }
                    },
                    "409": {
                        "description": "email已經被使用過",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "message": "email already exist"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "驗證請求有誤",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/validateError"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "登入",
                "operationId": "abc53c091ac89d7a2af0892997d1ee08",
                "requestBody": {
                    "request": "LoginRequestBody",
                    "description": "登入會員的請求範例",
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string",
                                        "example": "root@example.com"
                                    },
                                    "password": {
                                        "type": "string",
                                        "example": "12345678"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "user": {
                                        "id": 1,
                                        "name": "allen",
                                        "email": "allen@example.com",
                                        "phone": "0912345678",
                                        "address": null
                                    },
                                    "token": "2|UvEntO7H9iN4SF9eJYPNCxVbBN8V0Nv5TnANWUO9"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "email或password有誤",
                        "content": {
                            "application/json": {
                                "schema": {},
                                "example": {
                                    "message": "Credentials do not match records"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "登出",
                "operationId": "43958ea73917f8e50945f73452c3bff0",
                "responses": {
                    "204": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {}
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/api/user": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "用戶資料",
                "operationId": "9cd1cee912e0176094a7ec83cc9b432f",
                "responses": {
                    "200": {
                        "description": "請求成功",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/userInfo"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "inventoryReq": {
                "type": "object",
                "example": {
                    "inventory_id": 1,
                    "product_quantity": 3
                }
            },
            "inventoryReqs": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "$ref": "#/components/schemas/inventoryReq"
                        },
                        {
                            "$ref": "#/components/schemas/inventoryReq"
                        },
                        {
                            "$ref": "#/components/schemas/inventoryReq"
                        }
                    ]
                }
            },
            "myCartProduct": {
                "type": "object",
                "example": {
                    "id": 1,
                    "color": "灰色",
                    "size": "M",
                    "product_quantity": 5,
                    "name": "獨家帥氣T恤",
                    "price": 1500,
                    "category": "衣服",
                    "image": "https://via.placeholder.com/640x480.png/002255?text=dolorem"
                }
            },
            "myCartProducts": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "$ref": "#/components/schemas/myCartProduct"
                        },
                        {
                            "$ref": "#/components/schemas/myCartProduct"
                        },
                        {
                            "$ref": "#/components/schemas/myCartProduct"
                        }
                    ]
                }
            },
            "inventoryForChart": {
                "type": "object",
                "example": {
                    "id": 1,
                    "color": "灰色",
                    "size": "M",
                    "inventory_quantity": 5,
                    "name": "獨家帥氣T恤",
                    "price": 1500,
                    "category": "衣服",
                    "image": "https://via.placeholder.com/640x480.png/002255?text=dolorem"
                }
            },
            "inventoriesForChart": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "$ref": "#/components/schemas/inventoryForChart"
                        },
                        {
                            "$ref": "#/components/schemas/inventoryForChart"
                        },
                        {
                            "$ref": "#/components/schemas/inventoryForChart"
                        }
                    ]
                }
            },
            "image": {
                "type": "object",
                "example": {
                    "id": 1,
                    "url": "https://via.placeholder.com/640x480.png/002255?text=dolorem"
                }
            },
            "inventory": {
                "type": "object",
                "example": {
                    "id": 1,
                    "color": "黑色",
                    "size": "M",
                    "amount": 3
                }
            },
            "product": {
                "properties": {
                    "id": {
                        "type": "integer",
                        "example": "1"
                    },
                    "name": {
                        "type": "string",
                        "example": "NBA Sideline Pullover Satin Jacket 防風套衫 湖人 紫"
                    },
                    "price": {
                        "type": "integer",
                        "example": "1300"
                    },
                    "intro": {
                        "type": "string",
                        "example": "this is introduction"
                    },
                    "status": {
                        "description": "刪除、上架、下架",
                        "type": "integer",
                        "example": "上架"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "images": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "$ref": "#/components/schemas/image"
                                },
                                {
                                    "$ref": "#/components/schemas/image"
                                },
                                {
                                    "$ref": "#/components/schemas/image"
                                }
                            ]
                        }
                    },
                    "category": {
                        "type": "object",
                        "example": {
                            "id": 5,
                            "name": "上衣"
                        }
                    }
                },
                "type": "object"
            },
            "productsWithInventories": {
                "properties": {
                    "id": {
                        "type": "integer",
                        "example": "1"
                    },
                    "name": {
                        "type": "string",
                        "example": "NBA Sideline Pullover Satin Jacket 防風套衫 湖人 紫"
                    },
                    "price": {
                        "type": "integer",
                        "example": "1300"
                    },
                    "intro": {
                        "type": "string",
                        "example": "this is introduction"
                    },
                    "status": {
                        "description": "刪除、上架、下架",
                        "type": "integer",
                        "example": "上架"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "images": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "$ref": "#/components/schemas/image"
                                },
                                {
                                    "$ref": "#/components/schemas/image"
                                },
                                {
                                    "$ref": "#/components/schemas/image"
                                }
                            ]
                        }
                    },
                    "category": {
                        "type": "object",
                        "example": {
                            "id": 5,
                            "name": "上衣"
                        }
                    },
                    "inventories": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "$ref": "#/components/schemas/inventory"
                                },
                                {
                                    "$ref": "#/components/schemas/inventory"
                                },
                                {
                                    "$ref": "#/components/schemas/inventory"
                                }
                            ]
                        }
                    }
                },
                "type": "object"
            },
            "products": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "$ref": "#/components/schemas/product"
                        },
                        {
                            "$ref": "#/components/schemas/product"
                        },
                        {
                            "$ref": "#/components/schemas/product"
                        },
                        {
                            "$ref": "#/components/schemas/product"
                        },
                        {
                            "$ref": "#/components/schemas/product"
                        }
                    ]
                }
            },
            "validateError": {
                "properties": {
                    "message": {
                        "type": "string",
                        "example": "The name field is required."
                    },
                    "errors": {
                        "type": "object",
                        "example": {
                            "name": [
                                "The name field is required."
                            ]
                        }
                    }
                },
                "type": "object"
            },
            "userInfo": {
                "properties": {
                    "id": {
                        "type": "integer",
                        "example": 1
                    },
                    "name": {
                        "type": "string",
                        "example": "allen"
                    },
                    "email": {
                        "type": "string",
                        "example": "allen@example.com"
                    },
                    "phone": {
                        "type": "string",
                        "example": "0912345678"
                    },
                    "address": {
                        "type": "string",
                        "example": null
                    },
                    "carts": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {
                                    "$ref": "#/components/schemas/myCartProduct"
                                },
                                {
                                    "$ref": "#/components/schemas/myCartProduct"
                                },
                                {
                                    "$ref": "#/components/schemas/myCartProduct"
                                }
                            ]
                        }
                    }
                },
                "type": "object"
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "description": "call url /login, paste token value to here.",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "Users",
            "description": "使用者"
        },
        {
            "name": "Products",
            "description": "商品"
        },
        {
            "name": "Inventories",
            "description": "存貨"
        },
        {
            "name": "Carts",
            "description": "購物車"
        }
    ]
}